# Generated by Django 3.2.12 on 2022-05-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='now_playing',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
