# Generated by Django 3.2.12 on 2022-05-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_now_playing'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popular',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='upcoming',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
